import localFont from "next/font/local";
import "../globals.css";
import { RadixDappToolkit } from "@radixdlt/radix-dapp-toolkit";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
